---
  - name: Sub Task 1 => Get all users detail from the system
    ansible.builtin.shell:
      cmd: cat /etc/passwd | awk -F ":" '{print $1}'
    register: userNames

          
  - name: Sub Task 2 => Convert user details from dictionary to list
      set_fact:
        user_list: "{{userNames.stdout_lines}}"

          
  - name: Sub Task 3 => Update password only if user '{{ userName }}' exists
    ansible.builtin.shell:
      cmd: echo "{{userName}}:{{newPassword}}"| chpasswd -c
    when: userName in user_list
      
      
          
