
--- 

  - name: Task 1 => Retrieve group details - To verify whether the group '{{ groupName }}' to be deleted exists in the system
    getent:
      database: group
     
     
  - name: Task 2 => Check whether the group to be deleted '{{ groupName }}' already exists in the system
    assert:
      that:
        - groupName in getent_group.keys()
      fail_msg: "Status: Failed !!! Status Message: The group to be deleted '{{ groupName }}' does not exist in the system."


  - name: Task 3 => Delete the group '{{ groupName }}' in the system
    ansible.builtin.group:
      name: "{{ groupName }}"
      state: absent


  - name: Task 4 => Retrieve group details - To verify whether the group '{{ groupName }}' is deleted in the system
    getent:
      database: group


  - name: Task 6 => Check and confirm that the group '{{ groupName }}' is deleted  successfully
    assert:
      that:
        - groupName not in getent_group.keys()
      success_msg: "Status: Success!!! Status Message: Group '{{ groupName }}' is deleted successfully in the system" 
      fail_msg: "Status: Failure!!! Status Message: Deletion of group '{{ groupName }}' in the systme is failed"
  
