---

  - name: clean directory
    ansible.builtin.file:
      state: absent
      path: "{{ dest_dir }}"


  - name: Check out repository
    become: yes
    git:
      repo: 'https://{{git_token}}@github.com/{{repo}}'
      dest: "{{ dest_dir }}"
          
